site_name: Team Wiki
site_url: https://tensiondriven.github.io/kb/
repo_url: https://github.com/tensiondriven/kb
docs_dir: published
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top

nav:
  - Home: index.md
  - Governance:
    - Overview: gov/README.md
    - Roles: gov/roles/README.md
    - Policies: gov/policies/README.md
  - Operations:
    - Overview: ops/README.md
    - ProjectsByRole: ops/projects-by-role

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences