site_name: Team Wiki
site_url: https://example.com/wiki
repo_url: https://github.com/your-org/team-wiki
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top

nav:
  - Home: index.md
  - Governance:
    - Overview: gov/README.md
    - Roles: gov/roles/README.md
    - Responsibilities: gov/responsibilities/README.md
    - Policies: gov/policies/README.md
    - Schedules: gov/schedules/README.md
  - Operations:
    - Overview: ops/README.md
    - Projects: ops/projects/README.md
    - Tasks: ops/tasks/README.md
    - Research: ops/research/README.md
    - Synthesis: ops/synthesis/README.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences